import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { Button } from '@/components/Button';
import MissionAd from '@/components/MissionAd';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <Header />
        <MissionAd />
        <Button size='sm' variant='destructive'>
          Test
        </Button>
        {children}
      </body>
    </html>
  );
}
